import { createSlice, configureStore } from "@reduxjs/toolkit";

// Define the auth slice
const authSlice = createSlice({
    name: "auth",
    initialState: { user:"", isLoggedIn: false },
    reducers: { // Note the change from 'reducer' to 'reducers'
        login(state) {
            state.isLoggedIn = true ;
        },
        logout(state){
            state.isLoggedIn = false ;
        },
    },
});

// Export the actions generated by the slice
export const authActions = authSlice.actions;

// Create and configure the Redux store
export const store = configureStore({
    reducer: authSlice.reducer, 
});

export default store;
